### ISSUE TITLE
[Hive] error while creating uniform sample without ratio

### ISSUE THREAD

**Issue by dongyoungy** [mozafari/verdict#100]
This is not an urgent issue. I will open issues for bugs that I find while using verdict for future fixes.

I was trying to create uniform sample on one of the fact tables (i.e., store_sales) in TPC-DS using Hive and encountered the following error:

verdict:Apache Hive> create uniform sample of store_sales;
INFO   2018-03-02 15:36:24,273 - No sampling ratio provided; sample sizes are automatically determined to have at least 1 million tuples.
java.lang.StringIndexOutOfBoundsException: String index out of range: 1
	at java.lang.String.substring(String.java:1907)
	at edu.umich.verdict.dbms.DbmsJDBC.getColumns(DbmsJDBC.java:135)
	at edu.umich.verdict.VerdictMeta.refreshColumns(VerdictMeta.java:186)
	at edu.umich.verdict.VerdictMeta.getColumns(VerdictMeta.java:170)
	at edu.umich.verdict.query.CreateSampleQuery.heuristicSampleSizeSuggestion(CreateSampleQuery.java:71)
	at edu.umich.verdict.query.CreateSampleQuery.buildSamples(CreateSampleQuery.java:99)
	at edu.umich.verdict.query.CreateSampleQuery.compute(CreateSampleQuery.java:64)
	at edu.umich.verdict.query.Query.computeResultSet(Query.java:134)
	at edu.umich.verdict.VerdictJDBCContext.execute(VerdictJDBCContext.java:137)
	at edu.umich.verdict.VerdictContext.executeJdbcQuery(VerdictContext.java:148)
	at edu.umich.verdict.jdbc.VerdictStatement.execute(VerdictStatement.java:75)
	at sqlline.Commands.execute(Commands.java:874)
	at sqlline.Commands.sql(Commands.java:784)
	at sqlline.SqlLine.dispatch(SqlLine.java:880)
	at sqlline.SqlLine.begin(SqlLine.java:753)
	at sqlline.SqlLine.start(SqlLine.java:424)
	at sqlline.SqlLine.main(SqlLine.java:314)

Creating an uniform sample with a specified ratio (e.g. 'create 1% uniform sample of store_sales') seems to work fine.

**Comment by dongyoungy** [comment]
Merge #101 resolved this issue.
