### ISSUE TITLE
Redshift: Invalid operation: relation .. already exists;

### ISSUE THREAD

**Issue by RAbraham** [mozafari/verdict#85]
Hi,
After logging on, I ran the following and it errored out
```sql
set loglevel=debug;
create sample of myschema.mytable;
```
The full output.

```bash
verdict:PostgreSQL> set loglevel=debug;
DEBUG  2017-09-18 16:14:05,709 - [DbmsRedshift] About to run: select 1
DEBUG  2017-09-18 16:14:05,710 - [DbmsRedshift] Closed the statement with id: 1472465
DEBUG  2017-09-18 16:14:05,710 - [DbmsRedshift] A new statement id: 1224347463
DEBUG  2017-09-18 16:14:05,770 - [VerdictJDBCContext] The query execution finished.
DEBUG  2017-09-18 16:14:05,770 - [VerdictStatement] Internal statement set to 1224347463
No rows affected (0.254 seconds)
DEBUG  2017-09-18 16:14:05,771 - [DbmsRedshift] Closed the statement with id: 1224347463
verdict:PostgreSQL> create sample of myschema.mytable;
DEBUG  2017-09-18 16:14:27,010 - [VerdictStatement] execute() called with: create sample of myschema.mytable
DEBUG  2017-09-18 16:14:27,010 - [VerdictJDBCContext] An input query:
DEBUG  2017-09-18 16:14:27,010 - [VerdictJDBCContext]   create sample of myschema.mytable
DEBUG  2017-09-18 16:14:27,030 - [Class] [0] A query type: CREATE_SAMPLE
DEBUG  2017-09-18 16:14:27,033 - [DbmsRedshift] About to run: create schema if not exists myschema_verdict
DEBUG  2017-09-18 16:14:27,033 - [DbmsRedshift] Closed the statement with id: 1472682156
DEBUG  2017-09-18 16:14:27,033 - [DbmsRedshift] A new statement id: 178049969
DEBUG  2017-09-18 16:14:27,488 - [DbmsRedshift] About to run: select nspname from pg_namespace
DEBUG  2017-09-18 16:14:27,488 - [DbmsRedshift] Closed the statement with id: 178049969
DEBUG  2017-09-18 16:14:27,488 - [DbmsRedshift] A new statement id: 24119573
DEBUG  2017-09-18 16:14:27,583 - [DbmsRedshift] About to run: create schema if not exists myschema_verdict
DEBUG  2017-09-18 16:14:27,584 - [DbmsRedshift] Closed the statement with id: 24119573
DEBUG  2017-09-18 16:14:27,584 - [DbmsRedshift] A new statement id: 568221876
DEBUG  2017-09-18 16:14:27,995 - [DbmsRedshift] About to run: select nspname from pg_namespace
DEBUG  2017-09-18 16:14:27,995 - [DbmsRedshift] Closed the statement with id: 568221876
DEBUG  2017-09-18 16:14:27,995 - [DbmsRedshift] A new statement id: 203849460
INFO   2017-09-18 16:14:28,090 - [CreateSampleQuery] Create a 1.00% uniform random sample of myschema.mytable.
DEBUG  2017-09-18 16:14:28,091 - [DbmsRedshift] About to run: SELECT DISTINCT tablename FROM pg_table_def WHERE schemaname = 'myschema_verdict'
DEBUG  2017-09-18 16:14:28,091 - [DbmsRedshift] Closed the statement with id: 203849460
DEBUG  2017-09-18 16:14:28,091 - [DbmsRedshift] A new statement id: 820914198
DEBUG  2017-09-18 16:14:28,190 - [DbmsRedshift] Table, myschema_verdict.vs_mytable_uf_0_0100, does not exists. Verdict doesn't bother to run a drop table statement.
DEBUG  2017-09-18 16:14:28,244 - [DbmsRedshift] About to run: SELECT DISTINCT tablename FROM pg_table_def WHERE schemaname = 'myschema_verdict'
DEBUG  2017-09-18 16:14:28,244 - [DbmsRedshift] Closed the statement with id: 820914198
DEBUG  2017-09-18 16:14:28,244 - [DbmsRedshift] A new statement id: 1916575798
DEBUG  2017-09-18 16:14:28,339 - [DbmsRedshift] Table, myschema_verdict.vt48_1, does not exists. Verdict doesn't bother to run a drop table statement.
DEBUG  2017-09-18 16:14:28,341 - [DbmsRedshift] The query used for creating a temporary table without sampling probabilities:
DEBUG  2017-09-18 16:14:28,341 - [DbmsRedshift] create table myschema_verdict.vt48_1 as SELECT *, mod(cast(round((random() * 100)) as integer), 100) AS "verdict_vpart" FROM (SELECT *, random() AS "verdict_rand" FROM myschema.mytable AS vt1) AS vt2 WHERE "verdict_rand" < 0.010000
DEBUG  2017-09-18 16:14:28,363 - [DbmsRedshift]   CREATE TABLE myschema_verdict.vt48_1 AS
DEBUG  2017-09-18 16:14:28,364 - [DbmsRedshift]       SELECT *,
DEBUG  2017-09-18 16:14:28,364 - [DbmsRedshift]              mod(cast(round((random() * 100)) as integer), 100) AS "verdict_vpart"
DEBUG  2017-09-18 16:14:28,364 - [DbmsRedshift]       FROM (
DEBUG  2017-09-18 16:14:28,364 - [DbmsRedshift]            SELECT *,
DEBUG  2017-09-18 16:14:28,364 - [DbmsRedshift]                   random() AS "verdict_rand"
DEBUG  2017-09-18 16:14:28,364 - [DbmsRedshift]            FROM myschema.mytable vt1) vt2
DEBUG  2017-09-18 16:14:28,364 - [DbmsRedshift]       WHERE "verdict_rand" < 0.010000
DEBUG  2017-09-18 16:14:28,364 - [DbmsRedshift] About to run: create table myschema_verdict.vt48_1 as SELECT *, mod(cast(round((random() * 100)) as integer), 100) AS "verdict_vpart" FROM (SELECT *, random() AS "verdict_rand" FROM myschema.mytable AS vt1) AS vt2 WHERE "verdict_rand" < 0.010000
DEBUG  2017-09-18 16:14:28,364 - [DbmsRedshift] Closed the statement with id: 1916575798
DEBUG  2017-09-18 16:14:28,365 - [DbmsRedshift] A new statement id: 451460284
DEBUG  2017-09-18 16:14:32,215 - [AggregatedRelation] A query to db: SELECT count(*) AS "c_3" FROM myschema.mytable AS vt5
DEBUG  2017-09-18 16:14:32,216 - [AggregatedRelation] A query to db:
DEBUG  2017-09-18 16:14:32,217 - [AggregatedRelation]  SELECT count(*) AS "c_3"
DEBUG  2017-09-18 16:14:32,217 - [AggregatedRelation]  FROM myschema.mytable vt5
DEBUG  2017-09-18 16:14:32,217 - [DbmsRedshift] About to run: SELECT count(*) AS "c_3" FROM myschema.mytable AS vt5
DEBUG  2017-09-18 16:14:32,218 - [DbmsRedshift] Closed the statement with id: 451460284
DEBUG  2017-09-18 16:14:32,218 - [DbmsRedshift] A new statement id: 157168588
DEBUG  2017-09-18 16:14:33,332 - [AggregatedRelation] A query to db: SELECT count(*) AS "c_4" FROM myschema_verdict.vt48_1 AS vt7
DEBUG  2017-09-18 16:14:33,333 - [AggregatedRelation] A query to db:
DEBUG  2017-09-18 16:14:33,334 - [AggregatedRelation]  SELECT count(*) AS "c_4"
DEBUG  2017-09-18 16:14:33,334 - [AggregatedRelation]  FROM myschema_verdict.vt48_1 vt7
DEBUG  2017-09-18 16:14:33,334 - [DbmsRedshift] About to run: SELECT count(*) AS "c_4" FROM myschema_verdict.vt48_1 AS vt7
DEBUG  2017-09-18 16:14:33,334 - [DbmsRedshift] Closed the statement with id: 157168588
DEBUG  2017-09-18 16:14:33,334 - [DbmsRedshift] A new statement id: 1939022383
DEBUG  2017-09-18 16:14:34,436 - [DbmsRedshift] About to run: SELECT DISTINCT tablename FROM pg_table_def WHERE schemaname = 'myschema_verdict'
DEBUG  2017-09-18 16:14:34,436 - [DbmsRedshift] Closed the statement with id: 1939022383
DEBUG  2017-09-18 16:14:34,436 - [DbmsRedshift] A new statement id: 1911155630
DEBUG  2017-09-18 16:14:34,530 - [DbmsRedshift] Table, myschema_verdict.vs_mytable_uf_0_0100, does not exists. Verdict doesn't bother to run a drop table statement.
DEBUG  2017-09-18 16:14:34,531 - [DbmsRedshift] The query used for creating a temporary table without sampling probabilities:
DEBUG  2017-09-18 16:14:34,532 - [DbmsRedshift]   CREATE TABLE myschema_verdict.vs_mytable_uf_0_0100 AS
DEBUG  2017-09-18 16:14:34,532 - [DbmsRedshift]       SELECT *,
DEBUG  2017-09-18 16:14:34,533 - [DbmsRedshift]              (cast(23354 as float) / cast(2346532 as float)) AS "verdict_vprob"
DEBUG  2017-09-18 16:14:34,533 - [DbmsRedshift]       FROM myschema_verdict.vt48_1 vt9
DEBUG  2017-09-18 16:14:34,533 - [DbmsRedshift] create table myschema_verdict.vs_mytable_uf_0_0100 as SELECT *, (cast(23354 as float) / cast(2346532 as float)) AS "verdict_vprob" FROM myschema_verdict.vt48_1 AS vt9
DEBUG  2017-09-18 16:14:34,533 - [DbmsRedshift] About to run: create table myschema_verdict.vs_mytable_uf_0_0100 as SELECT *, (cast(23354 as float) / cast(2346532 as float)) AS "verdict_vprob" FROM myschema_verdict.vt48_1 AS vt9
DEBUG  2017-09-18 16:14:34,533 - [DbmsRedshift] Closed the statement with id: 1911155630
DEBUG  2017-09-18 16:14:34,533 - [DbmsRedshift] A new statement id: 1943634922
DEBUG  2017-09-18 16:14:34,735 - [VerdictStatement] edu.umich.verdict.exceptions.VerdictException: java.sql.SQLException: [Amazon](500310) Invalid operation: relation "vs_mytable_uf_0_0100" already exists;
	at com.amazon.redshift.client.messages.inbound.ErrorResponse.toErrorException(ErrorResponse.java:1830)
	at com.amazon.redshift.client.PGMessagingContext.handleErrorResponse(PGMessagingContext.java:822)
	at com.amazon.redshift.client.PGMessagingContext.handleMessage(PGMessagingContext.java:647)
	at com.amazon.jdbc.communications.InboundMessagesPipeline.getNextMessageOfClass(InboundMessagesPipeline.java:312)
	at com.amazon.redshift.client.PGMessagingContext.doMoveToNextClass(PGMessagingContext.java:1080)
	at com.amazon.redshift.client.PGMessagingContext.getErrorResponse(PGMessagingContext.java:1048)
	at com.amazon.redshift.client.PGClient.handleErrorsScenario3(PGClient.java:2510)
	at com.amazon.redshift.client.PGClient.handleErrors(PGClient.java:2375)
	at com.amazon.redshift.client.PGClient.directExecute(PGClient.java:1113)
	at com.amazon.redshift.client.PGClient.directExecuteExtraMetadata(PGClient.java:1182)
	at com.amazon.redshift.dataengine.PGQueryExecutor.execute(PGQueryExecutor.java:210)
	at com.amazon.jdbc.common.SStatement.executeNoParams(Unknown Source)
	at com.amazon.jdbc.common.SStatement.executeAnyUpdate(Unknown Source)
	at com.amazon.jdbc.common.SStatement.executeUpdate(Unknown Source)
	at edu.umich.verdict.dbms.DbmsJDBC.executeUpdate(DbmsJDBC.java:252)
	at edu.umich.verdict.dbms.DbmsRedshift.attachUniformProbabilityToTempTable(DbmsRedshift.java:111)
	at edu.umich.verdict.dbms.Dbms.createUniformRandomSampleTableOf(Dbms.java:304)
	at edu.umich.verdict.query.CreateSampleQuery.createUniformRandomSample(CreateSampleQuery.java:119)
	at edu.umich.verdict.query.CreateSampleQuery.buildSamples(CreateSampleQuery.java:57)
	at edu.umich.verdict.query.CreateSampleQuery.buildSamples(CreateSampleQuery.java:81)
	at edu.umich.verdict.query.CreateSampleQuery.compute(CreateSampleQuery.java:39)
	at edu.umich.verdict.query.Query.computeResultSet(Query.java:118)
	at edu.umich.verdict.VerdictJDBCContext.execute(VerdictJDBCContext.java:139)
	at edu.umich.verdict.VerdictContext.executeJdbcQuery(VerdictContext.java:143)
	at edu.umich.verdict.jdbc.VerdictStatement.execute(VerdictStatement.java:60)
	at sqlline.Commands.execute(Commands.java:859)
	at sqlline.Commands.sql(Commands.java:769)
	at sqlline.SqlLine.dispatch(SqlLine.java:885)
	at sqlline.SqlLine.begin(SqlLine.java:758)
	at sqlline.SqlLine.start(SqlLine.java:429)
Caused by: com.amazon.support.exceptions.ErrorException: [Amazon](500310) Invalid operation: relation "vs_mytable_uf_0_0100" already exists;
	... 30 more

	at edu.umich.verdict.dbms.DbmsJDBC.executeUpdate(DbmsJDBC.java:255)
	at edu.umich.verdict.dbms.DbmsRedshift.attachUniformProbabilityToTempTable(DbmsRedshift.java:111)
	at edu.umich.verdict.dbms.Dbms.createUniformRandomSampleTableOf(Dbms.java:304)
	at edu.umich.verdict.query.CreateSampleQuery.createUniformRandomSample(CreateSampleQuery.java:119)
	at edu.umich.verdict.query.CreateSampleQuery.buildSamples(CreateSampleQuery.java:57)
	at edu.umich.verdict.query.CreateSampleQuery.buildSamples(CreateSampleQuery.java:81)
	at edu.umich.verdict.query.CreateSampleQuery.compute(CreateSampleQuery.java:39)
	at edu.umich.verdict.query.Query.computeResultSet(Query.java:118)
	at edu.umich.verdict.VerdictJDBCContext.execute(VerdictJDBCContext.java:139)
	at edu.umich.verdict.VerdictContext.executeJdbcQuery(VerdictContext.java:143)
	at edu.umich.verdict.jdbc.VerdictStatement.execute(VerdictStatement.java:60)
	at sqlline.Commands.execute(Commands.java:859)
	at sqlline.Commands.sql(Commands.java:769)
	at sqlline.SqlLine.dispatch(SqlLine.java:885)
	at sqlline.SqlLine.begin(SqlLine.java:758)
	at sqlline.SqlLine.start(SqlLine.java:429)
	at sqlline.SqlLine.main(SqlLine.java:319)

Error: edu.umich.verdict.exceptions.VerdictException: java.sql.SQLException: [Amazon](500310) Invalid operation: relation "vs_mytable_uf_0_0100" already exists;
	at com.amazon.redshift.client.messages.inbound.ErrorResponse.toErrorException(ErrorResponse.java:1830)
	at com.amazon.redshift.client.PGMessagingContext.handleErrorResponse(PGMessagingContext.java:822)
	at com.amazon.redshift.client.PGMessagingContext.handleMessage(PGMessagingContext.java:647)
	at com.amazon.jdbc.communications.InboundMessagesPipeline.getNextMessageOfClass(InboundMessagesPipeline.java:312)
	at com.amazon.redshift.client.PGMessagingContext.doMoveToNextClass(PGMessagingContext.java:1080)
	at com.amazon.redshift.client.PGMessagingContext.getErrorResponse(PGMessagingContext.java:1048)
	at com.amazon.redshift.client.PGClient.handleErrorsScenario3(PGClient.java:2510)
	at com.amazon.redshift.client.PGClient.handleErrors(PGClient.java:2375)
	at com.amazon.redshift.client.PGClient.directExecute(PGClient.java:1113)
	at com.amazon.redshift.client.PGClient.directExecuteExtraMetadata(PGClient.java:1182)
	at com.amazon.redshift.dataengine.PGQueryExecutor.execute(PGQueryExecutor.java:210)
	at com.amazon.jdbc.common.SStatement.executeNoParams(Unknown Source)
	at com.amazon.jdbc.common.SStatement.executeAnyUpdate(Unknown Source)
	at com.amazon.jdbc.common.SStatement.executeUpdate(Unknown Source)
	at edu.umich.verdict.dbms.DbmsJDBC.executeUpdate(DbmsJDBC.java:252)
	at edu.umich.verdict.dbms.DbmsRedshift.attachUniformProbabilityToTempTable(DbmsRedshift.java:111)
	at edu.umich.verdict.dbms.Dbms.createUniformRandomSampleTableOf(Dbms.java:304)
	at edu.umich.verdict.query.CreateSampleQuery.createUniformRandomSample(CreateSampleQuery.java:119)
	at edu.umich.verdict.query.CreateSampleQuery.buildSamples(CreateSampleQuery.java:57)
	at edu.umich.verdict.query.CreateSampleQuery.buildSamples(CreateSampleQuery.java:81)
	at edu.umich.verdict.query.CreateSampleQuery.compute(CreateSampleQuery.java:39)
	at edu.umich.verdict.query.Query.computeResultSet(Query.java:118)
	at edu.umich.verdict.VerdictJDBCContext.execute(VerdictJDBCContext.java:139)
	at edu.umich.verdict.VerdictContext.executeJdbcQuery(VerdictContext.java:143)
	at edu.umich.verdict.jdbc.VerdictStatement.execute(VerdictStatement.java:60)
	at sqlline.Commands.execute(Commands.java:859)
	at sqlline.Commands.sql(Commands.java:769)
	at sqlline.SqlLine.dispatch(SqlLine.java:885)
	at sqlline.SqlLine.begin(SqlLine.java:758)
	at sqlline.SqlLine.start(SqlLine.java:429)
Caused by: com.amazon.support.exceptions.ErrorException: [Amazon](500310) Invalid operation: relation "vs_mytable_uf_0_0100" already exists;
	... 30 more

	at edu.umich.verdict.dbms.DbmsJDBC.executeUpdate(DbmsJDBC.java:255)
	at edu.umich.verdict.dbms.DbmsRedshift.attachUniformProbabilityToTempTable(DbmsRedshift.java:111)
	at edu.umich.verdict.dbms.Dbms.createUniformRandomSampleTableOf(Dbms.java:304)
	at edu.umich.verdict.query.CreateSampleQuery.createUniformRandomSample(CreateSampleQuery.java:119)
	at edu.umich.verdict.query.CreateSampleQuery.buildSamples(CreateSampleQuery.java:57)
	at edu.umich.verdict.query.CreateSampleQuery.buildSamples(CreateSampleQuery.java:81)
	at edu.umich.verdict.query.CreateSampleQuery.compute(CreateSampleQuery.java:39)
	at edu.umich.verdict.query.Query.computeResultSet(Query.java:118)
	at edu.umich.verdict.VerdictJDBCContext.execute(VerdictJDBCContext.java:139)
	at edu.umich.verdict.VerdictContext.executeJdbcQuery(VerdictContext.java:143)
	at edu.umich.verdict.jdbc.VerdictStatement.execute(VerdictStatement.java:60)
	at sqlline.Commands.execute(Commands.java:859)
	at sqlline.Commands.sql(Commands.java:769)
	at sqlline.SqlLine.dispatch(SqlLine.java:885)
	at sqlline.SqlLine.begin(SqlLine.java:758)
	at sqlline.SqlLine.start(SqlLine.java:429)
	at sqlline.SqlLine.main(SqlLine.java:319) (state=,code=0)
verdict:PostgreSQL>
```

**Comment by pyongjoo** [comment]
Thanks for the report. This seems that Verdict is not setting the search
path in Redshift properly. FYI, I don't think it would happen if "use
myschema" is used in advance before the sample creation statement, although
Verdict should just work without it.

I will investigate this issue and give you an update.

- Yongjoo

**Comment by RAbraham** [comment]
You are right, `use myschema` allowed me to progress further but I got another error. I'll create another ticket for it in case it is another issue.

**Comment by pyongjoo** [comment]
Hi Rajiv,

I sincerely apologize for the delays of this bug fix. I'm working on this right now and will give you an update.

Regards,
Young

**Comment by pyongjoo** [comment]
The fix for the bug has been pushed to the repository. With these changes, `show tables in db-name` (as well as other queries including sample creation statements) just works without setting redshift search_path.
