### ISSUE TITLE
[Spark] NullPointerException in create sample

### ISSUE THREAD

**Issue by mdashti** [mozafari/verdict#87]
Hi,

I wanted to checkout your awesome work in practice.

I started by creating a sample table, similar to the following `employee` table.
https://www.tutorialspoint.com/spark_sql/spark_sql_hive_tables.htm

Then, issued the following command:

```
vc.sql("create sample of employee").show(false)
```

And, unfortunately, I get the following error:

```
17/09/25 09:12:24 WARN metastore.ObjectStore: Failed to get database default_verdict, returning NoSuchObjectException
17/09/25 09:12:25 ERROR metastore.RetryingHMSHandler: AlreadyExistsException(message:Database default_verdict already exists)
	at org.apache.hadoop.hive.metastore.HiveMetaStore$HMSHandler.create_database(HiveMetaStore.java:944)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.hadoop.hive.metastore.RetryingHMSHandler.invokeInternal(RetryingHMSHandler.java:138)
	at org.apache.hadoop.hive.metastore.RetryingHMSHandler.invoke(RetryingHMSHandler.java:99)
	at com.sun.proxy.$Proxy35.create_database(Unknown Source)
	at org.apache.hadoop.hive.metastore.HiveMetaStoreClient.createDatabase(HiveMetaStoreClient.java:646)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.hadoop.hive.metastore.RetryingMetaStoreClient.invoke(RetryingMetaStoreClient.java:105)
	at com.sun.proxy.$Proxy36.createDatabase(Unknown Source)
	at org.apache.hadoop.hive.ql.metadata.Hive.createDatabase(Hive.java:345)
	at org.apache.hadoop.hive.ql.exec.DDLTask.createDatabase(DDLTask.java:3796)
	at org.apache.hadoop.hive.ql.exec.DDLTask.execute(DDLTask.java:268)
	at org.apache.hadoop.hive.ql.exec.Task.executeTask(Task.java:160)
	at org.apache.hadoop.hive.ql.exec.TaskRunner.runSequential(TaskRunner.java:100)
	at org.apache.hadoop.hive.ql.Driver.launchTask(Driver.java:1774)
	at org.apache.hadoop.hive.ql.Driver.execute(Driver.java:1531)
	at org.apache.hadoop.hive.ql.Driver.runInternal(Driver.java:1311)
	at org.apache.hadoop.hive.ql.Driver.run(Driver.java:1120)
	at org.apache.hadoop.hive.ql.Driver.run(Driver.java:1108)
	at org.apache.spark.sql.hive.client.ClientWrapper$$anonfun$runHive$1.apply(ClientWrapper.scala:486)
	at org.apache.spark.sql.hive.client.ClientWrapper$$anonfun$runHive$1.apply(ClientWrapper.scala:475)
	at org.apache.spark.sql.hive.client.ClientWrapper$$anonfun$withHiveState$1.apply(ClientWrapper.scala:281)
	at org.apache.spark.sql.hive.client.ClientWrapper.liftedTree1$1(ClientWrapper.scala:228)
	at org.apache.spark.sql.hive.client.ClientWrapper.retryLocked(ClientWrapper.scala:227)
	at org.apache.spark.sql.hive.client.ClientWrapper.withHiveState(ClientWrapper.scala:270)
	at org.apache.spark.sql.hive.client.ClientWrapper.runHive(ClientWrapper.scala:475)
	at org.apache.spark.sql.hive.client.ClientWrapper.runSqlHive(ClientWrapper.scala:465)
	at org.apache.spark.sql.hive.HiveContext.runSqlHive(HiveContext.scala:607)
	at org.apache.spark.sql.hive.execution.HiveNativeCommand.run(HiveNativeCommand.scala:33)
	at org.apache.spark.sql.execution.ExecutedCommand.sideEffectResult$lzycompute(commands.scala:58)
	at org.apache.spark.sql.execution.ExecutedCommand.sideEffectResult(commands.scala:56)
	at org.apache.spark.sql.execution.ExecutedCommand.doExecute(commands.scala:70)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$5.apply(SparkPlan.scala:132)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$5.apply(SparkPlan.scala:130)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:150)
	at org.apache.spark.sql.execution.SparkPlan.execute(SparkPlan.scala:130)
	at org.apache.spark.sql.execution.QueryExecution.toRdd$lzycompute(QueryExecution.scala:55)
	at org.apache.spark.sql.execution.QueryExecution.toRdd(QueryExecution.scala:55)
	at org.apache.spark.sql.DataFrame.<init>(DataFrame.scala:145)
	at org.apache.spark.sql.DataFrame.<init>(DataFrame.scala:130)
	at org.apache.spark.sql.DataFrame$.apply(DataFrame.scala:52)
	at org.apache.spark.sql.SQLContext.sql(SQLContext.scala:817)
	at edu.umich.verdict.dbms.DbmsSpark.execute(DbmsSpark.java:60)
	at edu.umich.verdict.dbms.DbmsSpark.executeUpdate(DbmsSpark.java:67)
	at edu.umich.verdict.dbms.Dbms.createCatalog(Dbms.java:203)
	at edu.umich.verdict.dbms.Dbms.createDatabase(Dbms.java:197)
	at edu.umich.verdict.query.CreateSampleQuery.buildSamples(CreateSampleQuery.java:53)
	at edu.umich.verdict.query.CreateSampleQuery.buildSamples(CreateSampleQuery.java:81)
	at edu.umich.verdict.query.CreateSampleQuery.compute(CreateSampleQuery.java:39)
	at edu.umich.verdict.query.Query.computeDataFrame(Query.java:137)
	at edu.umich.verdict.VerdictSparkHiveContext.execute(VerdictSparkHiveContext.java:68)
	at edu.umich.verdict.VerdictContext.executeSparkQuery(VerdictContext.java:153)
	at edu.umich.verdict.VerdictContext.sql(VerdictContext.java:165)
	at $line51.$read$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC.<init>(<console>:31)
	at $line51.$read$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC.<init>(<console>:36)
	at $line51.$read$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC.<init>(<console>:38)
	at $line51.$read$$iwC$$iwC$$iwC$$iwC$$iwC.<init>(<console>:40)
	at $line51.$read$$iwC$$iwC$$iwC$$iwC.<init>(<console>:42)
	at $line51.$read$$iwC$$iwC$$iwC.<init>(<console>:44)
	at $line51.$read$$iwC$$iwC.<init>(<console>:46)
	at $line51.$read$$iwC.<init>(<console>:48)
	at $line51.$read.<init>(<console>:50)
	at $line51.$read$.<init>(<console>:54)
	at $line51.$read$.<clinit>(<console>)
	at $line51.$eval$.<init>(<console>:7)
	at $line51.$eval$.<clinit>(<console>)
	at $line51.$eval.$print(<console>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.spark.repl.SparkIMain$ReadEvalPrint.call(SparkIMain.scala:1045)
	at org.apache.spark.repl.SparkIMain$Request.loadAndRun(SparkIMain.scala:1326)
	at org.apache.spark.repl.SparkIMain.loadAndRunReq$1(SparkIMain.scala:821)
	at org.apache.spark.repl.SparkIMain.interpret(SparkIMain.scala:852)
	at org.apache.spark.repl.SparkIMain.interpret(SparkIMain.scala:800)
	at org.apache.spark.repl.SparkILoop.reallyInterpret$1(SparkILoop.scala:857)
	at org.apache.spark.repl.SparkILoop.interpretStartingWith(SparkILoop.scala:902)
	at org.apache.spark.repl.SparkILoop.command(SparkILoop.scala:814)
	at org.apache.spark.repl.SparkILoop.processLine$1(SparkILoop.scala:657)
	at org.apache.spark.repl.SparkILoop.innerLoop$1(SparkILoop.scala:665)
	at org.apache.spark.repl.SparkILoop.org$apache$spark$repl$SparkILoop$$loop(SparkILoop.scala:670)
	at org.apache.spark.repl.SparkILoop$$anonfun$org$apache$spark$repl$SparkILoop$$process$1.apply$mcZ$sp(SparkILoop.scala:997)
	at org.apache.spark.repl.SparkILoop$$anonfun$org$apache$spark$repl$SparkILoop$$process$1.apply(SparkILoop.scala:945)
	at org.apache.spark.repl.SparkILoop$$anonfun$org$apache$spark$repl$SparkILoop$$process$1.apply(SparkILoop.scala:945)
	at scala.tools.nsc.util.ScalaClassLoader$.savingContextLoader(ScalaClassLoader.scala:135)
	at org.apache.spark.repl.SparkILoop.org$apache$spark$repl$SparkILoop$$process(SparkILoop.scala:945)
	at org.apache.spark.repl.SparkILoop.process(SparkILoop.scala:1064)
	at org.apache.spark.repl.Main$.main(Main.scala:31)
	at org.apache.spark.repl.Main.main(Main.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:731)
	at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:181)
	at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:206)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:121)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)

17/09/25 09:12:25 INFO util.VerdictLogger: Create a 1.00% uniform random sample of default.employee.
17/09/25 09:12:25 ERROR metadata.Hive: Table vs_employee_uf_0_0100 not found: default_verdict.vs_employee_uf_0_0100 table not found
17/09/25 09:12:25 ERROR metadata.Hive: Table vt34_5 not found: default_verdict.vt34_5 table not found
line 1:31 mismatched input 'default' expecting {FORCESEEK, VALUES, ABSOLUTE, APPLY, AUTO, AVG, BASE64, CALLER, CAST, CATCH, CHECKSUM_AGG, COMMITTED, CONCAT, COOKIE, COUNT, COUNT_BIG, DELAY, DELETED, DENSE_RANK, DISABLE, DYNAMIC, ENCRYPTION, EXTRACT, FAST, FAST_FORWARD, FIRST, FOLLOWING, FORWARD_ONLY, FULLSCAN, GLOBAL, GO, GROUPING, GROUPING_ID, HASH, INSENSITIVE, INSERTED, ISOLATION, KEEPFIXED, KEYSET, LAST, LEVEL, LOCAL, LOCK_ESCALATION, LOGIN, LOOP, MARK, MAX, MIN, MODIFY, NEXT, NAME, NOCOUNT, NOEXPAND, NORECOMPUTE, NTILE, NUMBER, OFFSET, ONLY, OPTIMISTIC, OPTIMIZE, OUT, OUTPUT, OWNER, PARTITION, PATH, PRECEDING, PRIOR, RANGE, RANK, READONLY, READ_ONLY, RECOMPILE, RELATIVE, REMOTE, REPEATABLE, ROOT, ROW, ROWGUID, ROWS, ROW_NUMBER, SAMPLE, SCHEMABINDING, SCROLL, SCROLL_LOCKS, SELF, SERIALIZABLE, SNAPSHOT, SPATIAL_WINDOW_MAX_CELLS, STATIC, STATS_STREAM, STDEV, STDEVP, SUM, STRTOL, THROW, TIES, TIME, TRY, TYPE, TYPE_WARNING, UNBOUNDED, UNCOMMITTED, UNKNOWN, USING, VAR, VARP, VIEW_METADATA, WORK, XML, XMLNAMESPACES, DOUBLE_QUOTE_ID, BACKTICK_ID, SQUARE_BRACKET_ID, ID, '('}
java.lang.NullPointerException
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visit(AbstractParseTreeVisitor.java:42)
	at edu.umich.verdict.relation.PrettyPrintVisitor.visitTable_source(Relation.java:769)
	at edu.umich.verdict.relation.PrettyPrintVisitor.visitTable_source(Relation.java:413)
	at edu.umich.verdict.parser.VerdictSQLParser$Table_sourceContext.accept(VerdictSQLParser.java:11562)
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visit(AbstractParseTreeVisitor.java:42)
	at edu.umich.verdict.relation.PrettyPrintVisitor.visitQuery_specification(Relation.java:475)
	at edu.umich.verdict.relation.PrettyPrintVisitor.visitQuery_specification(Relation.java:413)
	at edu.umich.verdict.parser.VerdictSQLParser$Query_specificationContext.accept(VerdictSQLParser.java:10385)
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visitChildren(AbstractParseTreeVisitor.java:70)
	at edu.umich.verdict.parser.VerdictSQLBaseVisitor.visitQuery_expression(VerdictSQLBaseVisitor.java:664)
	at edu.umich.verdict.parser.VerdictSQLParser$Query_expressionContext.accept(VerdictSQLParser.java:10149)
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visit(AbstractParseTreeVisitor.java:42)
	at edu.umich.verdict.relation.PrettyPrintVisitor.visitSelect_statement(Relation.java:450)
	at edu.umich.verdict.relation.PrettyPrintVisitor.visitSelect_statement(Relation.java:413)
	at edu.umich.verdict.parser.VerdictSQLParser$Select_statementContext.accept(VerdictSQLParser.java:1794)
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visitChildren(AbstractParseTreeVisitor.java:70)
	at edu.umich.verdict.parser.VerdictSQLBaseVisitor.visitVerdict_statement(VerdictSQLBaseVisitor.java:20)
	at edu.umich.verdict.parser.VerdictSQLParser$Verdict_statementContext.accept(VerdictSQLParser.java:375)
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visit(AbstractParseTreeVisitor.java:42)
	at edu.umich.verdict.relation.Relation.prettyfySql(Relation.java:248)
	at edu.umich.verdict.relation.Relation.collectDataFrame(Relation.java:173)
	at edu.umich.verdict.relation.Relation.collect(Relation.java:206)
	at edu.umich.verdict.relation.Relation.countValue(Relation.java:133)
	at edu.umich.verdict.dbms.Dbms.attachUniformProbabilityToTempTable(Dbms.java:337)
	at edu.umich.verdict.dbms.Dbms.createUniformRandomSampleTableOf(Dbms.java:314)
	at edu.umich.verdict.query.CreateSampleQuery.createUniformRandomSample(CreateSampleQuery.java:119)
	at edu.umich.verdict.query.CreateSampleQuery.buildSamples(CreateSampleQuery.java:57)
	at edu.umich.verdict.query.CreateSampleQuery.buildSamples(CreateSampleQuery.java:81)
	at edu.umich.verdict.query.CreateSampleQuery.compute(CreateSampleQuery.java:39)
	at edu.umich.verdict.query.Query.computeDataFrame(Query.java:137)
	at edu.umich.verdict.VerdictSparkHiveContext.execute(VerdictSparkHiveContext.java:68)
	at edu.umich.verdict.VerdictContext.executeSparkQuery(VerdictContext.java:153)
	at edu.umich.verdict.VerdictContext.sql(VerdictContext.java:165)
	at $iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC.<init>(<console>:31)
	at $iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC.<init>(<console>:36)
	at $iwC$$iwC$$iwC$$iwC$$iwC$$iwC.<init>(<console>:38)
	at $iwC$$iwC$$iwC$$iwC$$iwC.<init>(<console>:40)
	at $iwC$$iwC$$iwC$$iwC.<init>(<console>:42)
	at $iwC$$iwC$$iwC.<init>(<console>:44)
	at $iwC$$iwC.<init>(<console>:46)
	at $iwC.<init>(<console>:48)
	at <init>(<console>:50)
	at .<init>(<console>:54)
	at .<clinit>(<console>)
	at .<init>(<console>:7)
	at .<clinit>(<console>)
	at $print(<console>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.spark.repl.SparkIMain$ReadEvalPrint.call(SparkIMain.scala:1045)
	at org.apache.spark.repl.SparkIMain$Request.loadAndRun(SparkIMain.scala:1326)
	at org.apache.spark.repl.SparkIMain.loadAndRunReq$1(SparkIMain.scala:821)
	at org.apache.spark.repl.SparkIMain.interpret(SparkIMain.scala:852)
	at org.apache.spark.repl.SparkIMain.interpret(SparkIMain.scala:800)
	at org.apache.spark.repl.SparkILoop.reallyInterpret$1(SparkILoop.scala:857)
	at org.apache.spark.repl.SparkILoop.interpretStartingWith(SparkILoop.scala:902)
	at org.apache.spark.repl.SparkILoop.command(SparkILoop.scala:814)
	at org.apache.spark.repl.SparkILoop.processLine$1(SparkILoop.scala:657)
	at org.apache.spark.repl.SparkILoop.innerLoop$1(SparkILoop.scala:665)
	at org.apache.spark.repl.SparkILoop.org$apache$spark$repl$SparkILoop$$loop(SparkILoop.scala:670)
	at org.apache.spark.repl.SparkILoop$$anonfun$org$apache$spark$repl$SparkILoop$$process$1.apply$mcZ$sp(SparkILoop.scala:997)
	at org.apache.spark.repl.SparkILoop$$anonfun$org$apache$spark$repl$SparkILoop$$process$1.apply(SparkILoop.scala:945)
	at org.apache.spark.repl.SparkILoop$$anonfun$org$apache$spark$repl$SparkILoop$$process$1.apply(SparkILoop.scala:945)
	at scala.tools.nsc.util.ScalaClassLoader$.savingContextLoader(ScalaClassLoader.scala:135)
	at org.apache.spark.repl.SparkILoop.org$apache$spark$repl$SparkILoop$$process(SparkILoop.scala:945)
	at org.apache.spark.repl.SparkILoop.process(SparkILoop.scala:1064)
	at org.apache.spark.repl.Main$.main(Main.scala:31)
	at org.apache.spark.repl.Main.main(Main.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:731)
	at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:181)
	at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:206)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:121)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
```

Can you please have a look into it?

**Comment by pyongjoo** [comment]
Sorry for the error. I'll try to fix this within today.

**Comment by pyongjoo** [comment]
This bug has been fixed only syntactically (in our dev repo). But, since the dataset you tested was very small (which we didn't target in the first place), the current update may produce "null" values for `select count(*)` query. I will prevent such cases; then, push to the main repository.

**Comment by pyongjoo** [comment]
Our code (snapshot version) now works with the example you provided (i.e., `employee` table). Since the example table has only 5 tuples, you won't see any noticeable speedups in this case.

**Comment by mdashti** [comment]
Thanks for resolving the issue.
Do you have a tutorial style document for an end-to-end example? From data loading to running the queries?

**Comment by pyongjoo** [comment]
I apologize for a late response. Right now, the examples in our [Quick Start Guide](http://verdictdb.org/documentation/quick_start/) is what we have, which assumes that its readers have the basic understanding of Spark and other databases. However, I agree that having an end-to-end tutorial will be extremely useful. Although you might not benefit from it right now, we will work on this and leave a comment here when available. I'll keep this issue open until then.

**Comment by dongyoungy** [comment]
I am closing this issue as the problem has been resolved and OP has not been communicating for a longer than 6 months.
